name: Build app and run UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Selenium WebDriver UI Tests TestProject1
      run: dotnet test TestProject1 --no-build --verbosity normal
    - name: Run Selenium WebDriver UI Tests TestProject2
      run: dotnet test TestProject2 --no-build --verbosity normal
    - name: Run Selenium WebDriver UI Tests TestProject3
      run: dotnet test TestProject3 --no-build --verbosity normal
